### ISSUE TITLE
openssl recipe for target 'build_libs' failed

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/EtherollApp#124]
Building openssl after p4a update and pure `python3` migration fails.
The command was:
```
buildozer andoir debug
```
Relavant part of the error is:
```
/usr/bin/as: unrecognized option '-mfloat-abi=soft'                                                                                                                                                                         
```
More context:
```
...
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wall -fexceptions -MT src/java_raw_api.lo -MD -MP -MF src/.deps/java_raw_api.Tpo -c ../src/java_raw_api.c  -fPIC -DPIC -o src/.libs/java_raw_api.o
libtool: compile:  /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wall -fexceptions -MT src/closures.lo -MD -MP -MF src/.deps/closures.Tpo -c ../src/closures.c  -fPIC -DPIC -o src/.libs/closures.o
libtool: compile:  /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wall -fexceptions -MT src/java_raw_api.lo -MD -MP -MF src/.deps/java_raw_api.Tpo -c ../src/java_raw_api.c -o src/java_raw_api.o >/dev/null 2>&1
libtool: compile:  /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wall -fexceptions -MT src/closures.lo -MD -MP -MF src/.deps/closures.Tpo -c ../src/closures.c -o src/closures.o >/dev/null 2>&1
/bin/bash ./libtool  --tag=CC   --mode=link /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7  -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb  -Wall -fexceptions -no-undefined -avoid-version  -Xcompiler '--sysroot' '/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm' '-lm' '-L/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/libs_collections/etheroll/armeabi-v7a'  --sysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -lm -L/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/libs_collections/etheroll/armeabi-v7a -o libffi.la -rpath /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo                          src/arm/sysv.lo src/arm/ffi.lo
libtool: link: /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7 -shared  -fPIC -DPIC  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/arm/.libs/sysv.o src/arm/.libs/ffi.o   -L/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/libs_collections/etheroll/armeabi-v7a -lm  -mandroid -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -mandroid -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb --sysroot --sysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm   -Wl,-soname -Wl,libffi.so -o .libs/libffi.so
/home/andre/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_so.o: No such file or directory
/home/andre/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: fatal error: /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm: pread failed: Is a directory
collect2: error: ld returned 1 exit status
Makefile:1176: recipe for target 'libffi.la' failed
make[1]: *** [libffi.la] Error 1
make[1]: Leaving directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_19/libffi/arm-unknown-linux-androideabi'
Makefile:2368: recipe for target 'libffi.la' failed
make: *** [libffi.la] Error 2


  STDERR:


[INFO]:    make libffi.la failed as expected
[INFO]:    -> directory context /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_19/libffi
[INFO]:    <- directory context /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_19/libffi
[INFO]:    -> directory context /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_19/libffi/arm-unknown-linux-androideabi
[INFO]:    -> running ccache arm-linux-androideabi-gcc -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -mandroid -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platfo...(and 1750 more)
[INFO]:    <- directory context /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_target_19/libffi
[INFO]:    -> running cp -t /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/libs_collections/etheroll/armeabi-v7a /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/libffi/armeabi-v7a__ndk_ta...(and 60 more)
[INFO]:    <- directory context /home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    Building openssl for armeabi-v7a
[INFO]:    -> directory context /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1
[INFO]:    -> running perl Configure shared no-dso no-asm android-arm -D__ANDROID_API__=19
[INFO]:    Applying patch disable-sover.patch
[INFO]:    -> running patch -t -d /home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1 -p1 -i /home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-androi...(and 68 more)
[INFO]:    -> running make build_libs
Exception in thread background thread for pid 3644:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/andre/.local/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/andre/.local/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/andre/.local/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/andre/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2:

  RAN: /usr/bin/make build_libs

  STDOUT:
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _build_libs
make[1]: Entering directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1'
make[1]: Leaving directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1'
make[1]: Entering directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1'
/usr/bin/ccache /home/andre/.buildozer/android/platform/android-ndk-r9c/toolchains/llvm-3.3/prebuilt/linux-x86_64/bin/clang -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -target armv7a-none-linux-androideabi -gcc-toolchain /home/andre/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7  -I. -Iinclude -fPIC -pthread  -target armv5te-linux-androideabi -gcc-toolchain /home/andre/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=19 -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
/usr/bin/as: unrecognized option '-mfloat-abi=soft'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
Makefile:728: recipe for target 'apps/app_rand.o' failed
make[1]: *** [apps/app_rand.o] Error 1
make[1]: Leaving directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1'
Makefile:174: recipe for target 'build_libs' failed
make: *** [build_libs] Error 2


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 1039, in <module>
    main()
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 1033, in main
    ToolchainCL()
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 553, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 150, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/toolchain.py", line 191, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/build.py", line 633, in build_recipes
    recipe.build_arch(arch)
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/recipes/openssl/__init__.py", line 165, in build_arch
    shprint(sh.make, 'build_libs', _env=env)
  File "/home/andre/workspace/EtherollApp/.buildozer/android/platform/python-for-android-new-toolchain/pythonforandroid/logger.py", line 178, in shprint
    for line in output:
  File "/home/andre/.local/lib/python3.6/site-packages/sh.py", line 863, in next
    self.wait()
  File "/home/andre/.local/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/andre/.local/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2:

  RAN: /usr/bin/make build_libs

  STDOUT:
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _build_libs
make[1]: Entering directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1'
make[1]: Leaving directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1'
make[1]: Entering directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1'
/usr/bin/ccache /home/andre/.buildozer/android/platform/android-ndk-r9c/toolchains/llvm-3.3/prebuilt/linux-x86_64/bin/clang -DANDROID -fomit-frame-pointer -D__ANDROID_API__=19 -target armv7a-none-linux-androideabi -gcc-toolchain /home/andre/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64 -I/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -isysroot /home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -I/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/python-installs/etheroll/include/python2.7  -I. -Iinclude -fPIC -pthread  -target armv5te-linux-androideabi -gcc-toolchain /home/andre/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/andre/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm -Wall -O3 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG -D__ANDROID_API__=19 -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
/usr/bin/as: unrecognized option '-mfloat-abi=soft'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
Makefile:728: recipe for target 'apps/app_rand.o' failed
make[1]: *** [apps/app_rand.o] Error 1
make[1]: Leaving directory '/home/andre/workspace/EtherollApp/.buildozer/android/platform/build/build/other_builds/openssl/armeabi-v7a__ndk_target_19/openssl1.1'
Makefile:174: recipe for target 'build_libs' failed
make: *** [build_libs] Error 2


  STDERR:

# Command failed: /usr/bin/python3 -m pythonforandroid.toolchain create --dist_name=etheroll --bootstrap=sdl2 --requirements=android,attrdict==2.0.0,certifi==2018.10.15,cffi,chardet==3.0.4,cytoolz==0.9.0,eth-abi==1.2.2,eth-account==0.3.0,eth-hash==0.2.0,eth-keyfile==0.5.1,eth-keys==0.2.0b3,eth-rlp==0.1.2,eth-typing==2.0.0,eth-utils==1.2.1,gevent,hexbytes==0.1.0,https://github.com/AndreMiras/garden.layoutmargin/archive/20180517.tar.gz,https://github.com/AndreMiras/KivyMD/archive/69f3e88.tar.gz,https://github.com/AndreMiras/pyetheroll/archive/884805b.tar.gz,https://github.com/corpetty/py-etherscan-api/archive/cb91fb3.tar.gz,idna==2.7,kivy==1.10.1,lru-dict==1.1.5,openssl,oscpy==0.3.0,parsimonious==0.8.1,plyer==1.3.1,pycryptodome==3.4.6,Pygments==2.2.0,qrcode==6.0,raven==6.9.0,requests==2.20.0,requests-cache==0.4.13,rlp==1.0.3,setuptools,toolz==0.9.0,urllib3==1.24.1,web3==4.8.1 --arch armeabi-v7a --copy-libs --local-recipes /home/andre/workspace/EtherollApp/src/python-for-android/recipes --color=always --storage-dir="/home/andre/workspace/EtherollApp/.buildozer/android/platform/build"
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

**Comment by AndreMiras** [comment]
Got fixed somehow with recent upstream p4a updates
