### ISSUE TITLE
Flaky helper_test_roll_history test

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/EtherollApp#138]
In Travis only the following test seems flaky
```
 F
 ======================================================================
 FAIL: test_ui_base (tests.ui.test_etheroll_ui.UITestCase)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "/home/user/src/tests/ui/test_etheroll_ui.py", line 633, in test_ui_base
     app.run()
   File "/home/user/venv/lib/python3.6/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/home/user/venv/lib/python3.6/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/user/venv/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/home/user/venv/lib/python3.6/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/home/user/venv/lib/python3.6/site-packages/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/home/user/venv/lib/python3.6/site-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/home/user/src/tests/ui/test_etheroll_ui.py", line 618, in run_test
     self.helper_test_roll_history(app)
   File "/home/user/src/tests/ui/test_etheroll_ui.py", line 368, in helper_test_roll_history
     self.assertEqual(len(threading.enumerate()), 3)
 AssertionError: 2 != 3
 
 ----------------------------------------------------------------------
 Ran 1 test in 12.431s
```

**Comment by AndreMiras** [comment]
Should be fixed in eb843d9
