### ISSUE TITLE
F-Droid update fail

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/EtherollApp#167]
The build for the last release `v2019.1101` is failing https://f-droid.org/wiki/page/com.github.andremiras.etheroll/lastbuild_721203001
We need to at least adapt the F-Droid data for https://github.com/kivy/python-for-android/pull/1986 and https://github.com/AndreMiras/EtherollApp/commit/6027ad45dc5e22c5c81009bf543b1b7e8dd192ad

**Comment by AndreMiras** [comment]
This is going to be painful. I made the `metadata/com.github.andremiras.etheroll.yml` update on my local F-Droid server, but it eventually fail installing one of the pure Python dependency which requires at least Python3.6. However the F-Droid build server runs Debian Stretch which is Python3.5.
The error was:
```
DEBUG: buildserver > Given no hashes to check 0 links for project 'eth-abi': discarding no candidates
DEBUG: buildserver > ERROR: Could not find a version that satisfies the requirement eth-abi==2.0.0 (from -r requirements.txt (line 4)) (from versions: 0.5.0, 1.0.0b0, 1.0.0b1, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 2.0.0a1, 2.0.0b0, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0b5, 2.0.0b6, 2.0.0b7)
DEBUG: buildserver > Cleaning up...
DEBUG: buildserver >   Removing source in /tmp/pip-req-build-9w29q2wl
DEBUG: buildserver >   Removing source in /tmp/pip-install-70l52am1/attrdict
DEBUG: buildserver > Removed build tracker '/tmp/pip-req-tracker-645h2fzi'
DEBUG: buildserver > ERROR: No matching distribution found for eth-abi==2.0.0 (from -r requirements.txt (line 4))
DEBUG: buildserver > Exception information:
DEBUG: buildserver > Traceback (most recent call last):
DEBUG: buildserver >   File "/home/vagrant/build/com.github.andremiras.etheroll/.buildozer/android/platform/build/build/venv/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
DEBUG: buildserver >     status = self.run(options, args)
DEBUG: buildserver >   File "/home/vagrant/build/com.github.andremiras.etheroll/.buildozer/android/platform/build/build/venv/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 382, in run
DEBUG: buildserver >     resolver.resolve(requirement_set)
DEBUG: buildserver >   File "/home/vagrant/build/com.github.andremiras.etheroll/.buildozer/android/platform/build/build/venv/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
DEBUG: buildserver >     self._resolve_one(requirement_set, req)
DEBUG: buildserver >   File "/home/vagrant/build/com.github.andremiras.etheroll/.buildozer/android/platform/build/build/venv/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
DEBUG: buildserver >     abstract_dist = self._get_abstract_dist_for(req_to_install)
DEBUG: buildserver >   File "/home/vagrant/build/com.github.andremiras.etheroll/.buildozer/android/platform/build/build/venv/lib/python3.5/site-packages/pip/_internal/legacy_resolve.py", line 311, in _get_abstract_dist_for
DEBUG: buildserver >     req.populate_link(self.finder, upgrade_allowed, self.require_hashes)
DEBUG: buildserver >   File "/home/vagrant/build/com.github.andremiras.etheroll/.buildozer/android/platform/build/build/venv/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 225, in populate_link
DEBUG: buildserver >     self.link = finder.find_requirement(self, upgrade)
DEBUG: buildserver >   File "/home/vagrant/build/com.github.andremiras.etheroll/.buildozer/android/platform/build/build/venv/lib/python3.5/site-packages/pip/_internal/index.py", line 906, in find_requirement
DEBUG: buildserver >     'No matching distribution found for %s' % req
DEBUG: buildserver > pip._internal.exceptions.DistributionNotFound: No matching distribution found for eth-abi==2.0.0 (from -r requirements.txt (line 4))
```
I'm not too sure how to address it yet.
Some options I can think of:

1. try to force install/compile Python3.6 on F-Droid
2. try to use the already locally compiled host Python from p4a
3. try with `eth-abi== 2.0.0b7` which is the last one accepting Python3.5

**Comment by AndreMiras** [comment]
F-Droid pending PR https://gitlab.com/fdroid/fdroiddata/merge_requests/5897
