### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/EtherollApp#26]
After compiling the Android apk on buildozer, the file is not found for the deployment.
```
buildozer android debug deploy run
...
[INFO]:    <- directory context /home/andre/demo/.buildozer/android/platform/python-for-android-new-toolchain
[INFO]:    # Copying APK to current directory
[INFO]:    # Found APK file: /home/andre/demo/.buildozer/android/platform/build/dists/myapp/bin/MyApplication-0.1-debug.apk
[DEBUG]:   -> running cp /home/andre/demo/.buildozer/android/platform/build/dists/myapp/bin/MyApplication-0.1-debug.apk ./
b'Could not find hostpython, will not compile to .pyo (this is normal with python3)\nNo compiled python is present to zip, skipping.\nthis should only be the case if you are using the CrystaX python\n'Traceback (most recent call last):
  File "/home/andre/.local/bin/buildozer", line 11, in <module>
    load_entry_point('buildozer==0.34', 'console_scripts', 'buildozer')()
  File "/home/andre/.local/lib64/python3.5/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/home/andre/.local/lib64/python3.5/site-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/home/andre/.local/lib64/python3.5/site-packages/buildozer/target.py", line 92, in run_commands
    func(args)
  File "/home/andre/.local/lib64/python3.5/site-packages/buildozer/target.py", line 104, in cmd_debug
    self.buildozer.build()
  File "/home/andre/.local/lib64/python3.5/site-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/home/andre/.local/lib64/python3.5/site-packages/buildozer/targets/android.py", line 817, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/usr/lib64/python3.5/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/andre/demo/.buildozer/android/platform/build/dists/myapp/build/outputs/apk/myapp-debug.apk'
```
This is a known buildozer issue https://github.com/kivy/buildozer/issues/312

**Comment by AndreMiras** [comment]
Applying proposed patch should fix it.
https://github.com/kivy/buildozer/issues/312#issuecomment-354456351
I'll leave the ticket open until this is fixed in buildozer so no manual patching is needed.

**Comment by AndreMiras** [comment]
The fix integrated to `buildozer==0.34` may not fix it. See my comment to workaround it:
https://github.com/kivy/buildozer/issues/599#issuecomment-377631623

**Comment by AndreMiras** [comment]
Another comment related to the issue: https://github.com/kivy/buildozer/commit/83ad94d6260cf6cb34711d27a224dbca97ec1c20#r29065648
