### ISSUE TITLE
Gevent compilation issues

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/EtherollApp#29]
```
INFO]:    Building gevent for armeabi-v7a
[INFO]:    gevent apparently isn't already in site-packages
[INFO]:    Building compiled components in gevent
[INFO]:    -> directory context /home/ubuntu/demo/.buildozer/android/platform/build/build/other_builds/gevent-python3crystax/armeabi-v7a/gevent
[INFO]:    -> running python3.5 setup.py build_ext -v
           working: error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                   Exception in thread background thread for pid 27865:                                                                                
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 2170, in background_thread
    handle_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 1929, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
ErrorReturnCode_1: 

  RAN: /usr/bin/python3.5 setup.py build_ext -v

  STDOUT:
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'setup_requires'
  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
running build_ext
Running '(cd  "/home/ubuntu/demo/.buildozer/android/platform/build/build/other_builds/gevent-python3crystax/armeabi-v7a/gevent/libev"  && /bin/sh ./configure --host=arm-linux-androideabi  && cp config.h "$OLDPWD" ) > configure-output.txt' in /home/ubuntu/demo/.buildo
zer/android/platform/build/build/other_builds/gevent-python3crystax/armeabi-v7a/gevent/build/temp.linux-x86_64-3.5/libev
configure: WARNING: using cross tools not prefixed with host triplet
building 'gevent.corecext' extension
creating build/temp.linux-x86_64-3.5/gevent
/usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=19 -I/vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -isysroot /vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -I/home/u
buntu/demo/.buildozer/android/platform/build/build/python-installs/myapp/include/python3.5 -I/vagrant/crystax-ndk-10.3.2-linux-x86_64/sources/python/3.5/include/python/ -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -DANDROID -mandroid -fomit-frame-pointer -D__AND
ROID_API__=19 -I/vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -isysroot /vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -I/home/ubuntu/demo/.buildozer/android/platform/build/build/python-installs/myapp/include/python3.5
 -I/vagrant/crystax-ndk-10.3.2-linux-x86_64/sources/python/3.5/include/python/ -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibu
ild/temp.linux-x86_64-3.5/libev -Ilibev -I/usr/include/python3.5m -c gevent/gevent.corecext.c -o build/temp.linux-x86_64-3.5/gevent/gevent.corecext.o
In file included from gevent/libev.h:2:0,
                 from gevent/gevent.corecext.c:241:
libev/ev.c:483:48: warning: "/*" within comment [-Wcomment]
 /*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
...
...
...
gevent/gevent.corecext.c: In function '__pyx_pf_6gevent_8corecext_5child_6active___get__':
gevent/gevent.corecext.c:32955:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   if ((ev_is_active((&__pyx_v_self->_watcher)) != 0)) {
   ^
gevent/gevent.corecext.c: In function '__pyx_pf_6gevent_8corecext_5child_7pending___get__':
gevent/gevent.corecext.c:33016:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   if ((ev_is_pending((&__pyx_v_self->_watcher)) != 0)) {
   ^
gevent/gevent.corecext.c: In function '__pyx_pf_6gevent_8corecext_5child_6__init__':
gevent/gevent.corecext.c:33214:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   ev_child_init((&__pyx_v_self->_watcher), ((void *)gevent_callback_child), __pyx_v_pid, __pyx_v_trace);
   ^
gevent/gevent.corecext.c:33214:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gevent/gevent.corecext.c:33214:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gevent/gevent.corecext.c:33214:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/gevent
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro --sysroot /vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -lm -L/home/ubuntu/demo/.buildozer/android/platform/build/build/libs_collecti
ons/myapp/armeabi-v7a -L/vagrant/crystax-ndk-10.3.2-linux-x86_64/sources/crystax/libs/armeabi-v7a -lcrystax -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=19 -I/vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -isysroot /vagrant/cryst
ax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -I/home/ubuntu/demo/.buildozer/android/platform/build/build/python-installs/myapp/include/python3.5 -I/vagrant/crystax-ndk-10.3.2-linux-x86_64/sources/python/3.5/include/python/ -march=armv7-a -mfloat-abi=softf
p -mfpu=vfp -mthumb -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/gevent/gevent.corecext.o -o build/lib.linux-x86_64-3.5/gevent/corecext.cpython-35m-x86_64-linux-gnu.so
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mfloat-abi=softfp'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mfpu=vfp'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mthumb'
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


  STDERR:


Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/python-for-android/pythonforandroid/toolchain.py", line 978, in <module>
    main()
  File "/home/ubuntu/python-for-android/pythonforandroid/toolchain.py", line 975, in main
    ToolchainCL()
  File "/home/ubuntu/python-for-android/pythonforandroid/toolchain.py", line 512, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/home/ubuntu/python-for-android/pythonforandroid/toolchain.py", line 149, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/home/ubuntu/python-for-android/pythonforandroid/toolchain.py", line 193, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "pythonforandroid/build.py", line 574, in build_recipes
  File "pythonforandroid/recipe.py", line 847, in build_arch
  File "pythonforandroid/recipe.py", line 859, in build_compiled_components
  File "pythonforandroid/logger.py", line 175, in shprint
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 720, in next
    self.wait()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 651, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/sh.py", line 672, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python3.5 setup.py build_ext -v

  STDOUT:
...
...
gevent/gevent.corecext.c:33214:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gevent/gevent.corecext.c:33214:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
gevent/gevent.corecext.c:33214:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/gevent
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro --sysroot /vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -lm -L/home/ubuntu/demo/.buildozer/android/platform/build/build/libs_collections/myapp/armeabi-v7a -L/vagrant/crystax-ndk-10.3.2-linux-x86_64/sources/crystax/libs/armeabi-v7a -lcrystax -DANDROID -mandroid -fomit-frame-pointer -D__ANDROID_API__=19 -I/vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -isysroot /vagrant/crystax-ndk-10.3.2-linux-x86_64/platforms/android-19/arch-arm -I/home/ubuntu/demo/.buildozer/android/platform/build/build/python-installs/myapp/include/python3.5 -I/vagrant/crystax-ndk-10.3.2-linux-x86_64/sources/python/3.5/include/python/ -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/gevent/gevent.corecext.o -o build/lib.linux-x86_64-3.5/gevent/corecext.cpython-35m-x86_64-linux-gnu.so
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mfloat-abi=softfp'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mfpu=vfp'
x86_64-linux-gnu-gcc: error: unrecognized command line option '-mthumb'
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


  STDERR:

# Command failed: /usr/bin/python -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3crystax,kivy,setuptools,hostpython3crystax,gevent --arch armeabi-v7a --copy-libs --color=always --storage-dir=/home/ubuntu/demo/.buildozer/android/platform/build
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```

Upstream issue https://github.com/kivy/python-for-android/pull/1251

**Comment by AndreMiras** [comment]
Pull request merged upstream
