### ISSUE TITLE
PyYAML ImportError: No module named 'error'

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/EtherollApp#31]
See trace below:
```
04-03 22:33:06.777  7579  7642 I python  :  Traceback (most recent call last):
04-03 22:33:06.777  7579  7642 I python  :    File "main.py", line 16, in <module>
04-03 22:33:06.778  7579  7642 I python  :      from pyethapp.accounts import AccountsService
04-03 22:33:06.778  7579  7642 I python  :    File "/data/user/0/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/pyethapp/accounts.py", line 9, in <module>
04-03 22:33:06.779  7579  7642 I python  :      from ethereum.tools import keys
04-03 22:33:06.779  7579  7642 I python  :    File "/data/user/0/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/ethereum/tools/__init__.py", line 1, in <module>
04-03 22:33:06.780  7579  7642 I python  :      from ethereum.tools import keys, new_statetest_utils, testutils, tester, _solidity
04-03 22:33:06.780  7579  7642 I python  :    File "/data/user/0/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/ethereum/tools/new_statetest_utils.py", line 1, in <module>
04-03 22:33:06.780  7579  7642 I python  :      from ethereum.state import State
04-03 22:33:06.781  7579  7642 I python  :    File "/data/user/0/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/ethereum/state.py", line 8, in <module>
04-03 22:33:06.781  7579  7642 I python  :      from ethereum import trie
04-03 22:33:06.782  7579  7642 I python  :    File "/data/user/0/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/ethereum/trie.py", line 6, in <module>
04-03 22:33:06.782  7579  7642 I python  :      from ethereum.abi import is_string
04-03 22:33:06.782  7579  7642 I python  :    File "/data/user/0/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/ethereum/abi.py", line 9, in <module>
04-03 22:33:06.783  7579  7642 I python  :      import yaml
04-03 22:33:06.783  7579  7642 I python  :    File "/data/user/0/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/yaml/__init__.py", line 2, in <module>
04-03 22:33:06.784  7579  7642 I python  :      from error import *
04-03 22:33:06.784  7579  7642 I python  :  ImportError: No module named 'error'
04-03 22:33:06.969  7579  7642 I python  : Python for android ended.
```
This is because PyYAML will install the module for Python2 if you run Buildozer from Python2.

**Comment by AndreMiras** [comment]
Workaround with custom recipe https://github.com/AndreMiras/EtherollApp/commit/4be6be697c98b2aa6fded70391493961afde803e#diff-fe722ecaea583ed70b6bc4df7dd541a3 since it will pickup Crystax hostpython (3.5) for installing.
