### ISSUE TITLE
Android test (failures=1, errors=3)

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/EtherollApp#74]
Now that #69 is implemented, I could run tests on Android and saw few are failing, se log below:
```
test_hashlib_sha3 (tests.test_import.ModulesImportTestCase) ... ok
test_pyethapp (tests.test_import.ModulesImportTestCase) ... ok
test_pyethash (tests.test_import.ModulesImportTestCase) ... ERROR
test_pyethereum (tests.test_import.ModulesImportTestCase) ... ok
test_scrypt (tests.test_import.ModulesImportTestCase) ... ERROR
test_delete_account (tests.test_ethereum_utils.TestAccountUtils) ... ok
test_delete_account_already_exists (tests.test_ethereum_utils.TestAccountUtils) ... ok
test_deleted_account_dir (tests.test_ethereum_utils.TestAccountUtils) ... ok
test_new_account (tests.test_ethereum_utils.TestAccountUtils) ... ok
test_compute_profit (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_bet_results_logs (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_bets_logs (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_last_bets_blocks (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_last_bets_transactions (tests.test_pyetheroll.TestEtheroll) ... ERROR
test_get_log_bet_events (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_log_result_events (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_logs_url (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_logs_url_topics (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_merged_logs (tests.test_pyetheroll.TestEtheroll) ... ok
test_get_merged_logs_empty (tests.test_pyetheroll.TestEtheroll) ... ok
test_init (tests.test_pyetheroll.TestEtheroll) ... ok
test_merge_logs (tests.test_pyetheroll.TestEtheroll) ... ok
test_player_roll_dice (tests.test_pyetheroll.TestEtheroll) ... FAIL
test_decode_transaction_logs (tests.test_pyetheroll.TestTransactionDebugger) ... ok
test_decode_contract_call (tests.test_pyetheroll.TestUtils) ... ok
test_decode_method_log1 (tests.test_pyetheroll.TestUtils) ... ok
test_decode_method_log_bet (tests.test_pyetheroll.TestUtils) ... ok

======================================================================
ERROR: test_pyethash (tests.test_import.ModulesImportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_import.py", line 10, in test_pyethash
    import pyethash
ImportError: dlopen failed: cannot locate symbol "__bswap_64" referenced by "/data/data/com.github.andremiras.etheroll/files/app/crystax_python/site-packages/pyethash.so"...

======================================================================
ERROR: test_scrypt (tests.test_import.ModulesImportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_import.py", line 20, in test_scrypt
    import scrypt
ModuleNotFoundError: No module named 'scrypt'

======================================================================
ERROR: test_get_last_bets_transactions (tests.test_pyetheroll.TestEtheroll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_pyetheroll.py", line 608, in test_get_last_bets_transactions
    address=address, page=page, offset=offset)
  File "./pyetheroll.py", line 442, in get_last_bets_transactions
    date_time = datetime.utcfromtimestamp(int(timestamp, 16))
OverflowError: timestamp out of range for platform time_t

======================================================================
FAIL: test_player_roll_dice (tests.test_pyetheroll.TestEtheroll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_pyetheroll.py", line 534, in test_player_roll_dice
    self.assertEqual(m_signTransaction.call_args_list, expected_calls)
AssertionError: [call({'chainId': 1, 'gas': 310000, 'gasPr[294 chars]]*')] != [(({'nonce': 0, 'chainId': 1, 'to': '0x048[293 chars]'),)]

----------------------------------------------------------------------
Ran 27 tests in 111.054s

FAILED (failures=1, errors=3)
```

**Comment by AndreMiras** [comment]
Closing the parent task as 3/4 of the subtasks have been fixed.
Last issue is tracked under #79.
